name: corbanmailloux
markdown: redcarpet
pygments: true
encoding: UTF-8

url: http://corbanmailloux.github.io

# Owner/author information
owner:
    name:           Corban
    full-name:      Corban Mailloux
    # Gravatar Image (used in About Page)
    image: 			http://s.gravatar.com/avatar/3993a2a8a38ac82b7f8ba71defb76031
