name: corbanmailloux
markdown: redcarpet
highlighter: pygments
encoding: UTF-8

url: http://corb.co

# Owner/author information
owner:
    name:           Corban
    full-name:      Corban Mailloux
    # Gravatar Image (used in About Page)
    image:          http://s.gravatar.com/avatar/3993a2a8a38ac82b7f8ba71defb76031

# Limit what is hosted on the site.
exclude: ["runServer.bat", "CNAME", "corbanmailloux.github.io Project.sublime-project", "corbanmailloux.github.io Project.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md"]


collections:
  projects:
    output: true
    permalink: /projects/:path/
  projectgroups:
    output: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      layout: "project"
      group: "uncategorized"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "projectgroups"
    values:
      weight: 10

